name: Build Releases
on:
  push:
    tags:
      - v*.*.*

env:
  CGO_ENABLED: 0

jobs:
  build-cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.18
        os:
          - linux
          - darwin
          - windows
        arch:
          - amd64
          - 386
          - arm64
          - arm
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -o askai_${{ matrix.os }}_${{ matrix.arch }} main.go
          zip askai_${{ matrix.os }}_${{ matrix.arch }}.zip askai_${{ matrix.os }}_${{ matrix.arch }}

      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        with:
          files: askai_${{ matrix.os }}_${{ matrix.arch }}.zip
          prerelease: ${{ contains(github.ref, '-') }}
